# public inputs
merkle_root = "14083744074067644124300005811805206913179988037736503175887795857385708527984"

allowed_tokens = [
  "100",
  "200",
  "300",
]

# private inputs
[[txs]]
[txs.tx_data]
chain_id = "1"
sender = "11"
time = "1000"
amount = "0"
token_id = "100"
[txs.merkle_witness]
leaf = "11661796452214782231918905244658373549555324403051414610886365161420470121221"
index = "0"
siblings = [
  "7090456707781665978998832229353364552074158392896148583286053210216979915166",
  "14809794539469953955208972076465075579322340976908182430086360781867132421877",
  "1351624850847386537135803837276074034133380604636125509348841733872232657328",
]

[[txs]]
[txs.tx_data]
chain_id = "1"
sender = "12"
time = "1001"
amount = "1"
token_id = "100"
[txs.merkle_witness]
leaf = "7090456707781665978998832229353364552074158392896148583286053210216979915166"
index = "1"
siblings = [
  "11661796452214782231918905244658373549555324403051414610886365161420470121221",
  "14809794539469953955208972076465075579322340976908182430086360781867132421877",
  "1351624850847386537135803837276074034133380604636125509348841733872232657328",
]

[[txs]]
[txs.tx_data]
chain_id = "1"
sender = "13"
time = "1002"
amount = "2"
token_id = "100"
[txs.merkle_witness]
leaf = "12470129438174865803313433361972202529808622757303322681443542589174953056413"
index = "2"
siblings = [
  "3741356229674029711108045424498655624170707834655023258564755660570697977049",
  "20423679850506564072712693303886031027451993762372395462778134244279381592718",
  "1351624850847386537135803837276074034133380604636125509348841733872232657328",
]

[[txs]]
[txs.tx_data]
chain_id = "1"
sender = "14"
time = "1003"
amount = "3"
token_id = "100"
[txs.merkle_witness]
leaf = "3741356229674029711108045424498655624170707834655023258564755660570697977049"
index = "3"
siblings = [
  "12470129438174865803313433361972202529808622757303322681443542589174953056413",
  "20423679850506564072712693303886031027451993762372395462778134244279381592718",
  "1351624850847386537135803837276074034133380604636125509348841733872232657328",
]

[[txs]]
[txs.tx_data]
chain_id = "1"
sender = "15"
time = "1004"
amount = "4"
token_id = "100"
[txs.merkle_witness]
leaf = "20966607360388951041360497694598751149588081583066088317154981563342198387337"
index = "4"
siblings = [
  "13501536015444166010849575163613754159861820407334581821597908844991511093671",
  "3713810465380526972370075294469051504993557608543159221589679694401596309453",
  "11665570330232354422612908210931454026199553961329597106882793383961869024650",
]

[[txs]]
[txs.tx_data]
chain_id = "1"
sender = "16"
time = "1005"
amount = "5"
token_id = "100"
[txs.merkle_witness]
leaf = "13501536015444166010849575163613754159861820407334581821597908844991511093671"
index = "5"
siblings = [
  "20966607360388951041360497694598751149588081583066088317154981563342198387337",
  "3713810465380526972370075294469051504993557608543159221589679694401596309453",
  "11665570330232354422612908210931454026199553961329597106882793383961869024650",
]

[[txs]]
[txs.tx_data]
chain_id = "1"
sender = "17"
time = "1006"
amount = "6"
token_id = "100"
[txs.merkle_witness]
leaf = "20530200974335838896502665774289859891901840102313848602543806791364726420229"
index = "6"
siblings = [
  "10120142637994421880419715760039843668009007159724287720776588554081133718977",
  "9749911548599161226414170474209992119775412195762685766162454197008848770872",
  "11665570330232354422612908210931454026199553961329597106882793383961869024650",
]

[[txs]]
[txs.tx_data]
chain_id = "1"
sender = "18"
time = "1007"
amount = "7"
token_id = "100"
[txs.merkle_witness]
leaf = "10120142637994421880419715760039843668009007159724287720776588554081133718977"
index = "7"
siblings = [
  "20530200974335838896502665774289859891901840102313848602543806791364726420229",
  "9749911548599161226414170474209992119775412195762685766162454197008848770872",
  "11665570330232354422612908210931454026199553961329597106882793383961869024650",
]

