# public inputs
merkle_root = "2643021468297453499851515284980395843699180103854852140659542342283254751912"

# private inputs
[[txs]]
tx_data = "0"
[txs.merkle_witness]
leaf = "1"
index = "0"
siblings = [
  "2",
  "17380952042446168291178743041044530828369674063485643659763567652647121881611",
  "15894561042126677602478866251981380308532972212781201775474357351932367051138",
]

[[txs]]
tx_data = "1"
[txs.merkle_witness]
leaf = "2"
index = "1"
siblings = [
  "1",
  "17380952042446168291178743041044530828369674063485643659763567652647121881611",
  "15894561042126677602478866251981380308532972212781201775474357351932367051138",
]

[[txs]]
tx_data = "2"
[txs.merkle_witness]
leaf = "3"
index = "2"
siblings = [
  "4",
  "1594597865669602199208529098208508950092942746041644072252494753744672355203",
  "15894561042126677602478866251981380308532972212781201775474357351932367051138",
]

[[txs]]
tx_data = "3"
[txs.merkle_witness]
leaf = "4"
index = "3"
siblings = [
  "3",
  "1594597865669602199208529098208508950092942746041644072252494753744672355203",
  "15894561042126677602478866251981380308532972212781201775474357351932367051138",
]

[[txs]]
tx_data = "4"
[txs.merkle_witness]
leaf = "5"
index = "4"
siblings = [
  "6",
  "14238249223938691303147797241445406391754730321105987504683642791543592162684",
  "18145963038378645805713504092197197549342394757429773105454438568839292866655",
]

[[txs]]
tx_data = "5"
[txs.merkle_witness]
leaf = "6"
index = "5"
siblings = [
  "5",
  "14238249223938691303147797241445406391754730321105987504683642791543592162684",
  "18145963038378645805713504092197197549342394757429773105454438568839292866655",
]

[[txs]]
tx_data = "6"
[txs.merkle_witness]
leaf = "7"
index = "6"
siblings = [
  "8",
  "12096576599834478317592210225257899548976626129824898535087186730386772533086",
  "18145963038378645805713504092197197549342394757429773105454438568839292866655",
]

[[txs]]
tx_data = "7"
[txs.merkle_witness]
leaf = "8"
index = "7"
siblings = [
  "7",
  "12096576599834478317592210225257899548976626129824898535087186730386772533086",
  "18145963038378645805713504092197197549342394757429773105454438568839292866655",
]